format_version: 10
pipelines:
  pipelineAsScriptnew:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-6043eddd:
        git: https://github.com/pravatvmware/getting-started-repo
        shallow_clone: false
        auto_update: true       
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          buildJob:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Hello
                command: ./build
                run_if: passed
